FROM python:3.11-slim

WORKDIR /app

RUN pip install mlflow==2.16.0 && \
    apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

# Create directories
RUN mkdir -p /app/mlruns /app/artifacts

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "file:///app/mlruns", "--default-artifact-root", "/app/artifacts"]
